name: Keep Railway DB Awake

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping_n8n:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n keepalive webhook
        run: |
          curl -sSf https://n8n-x53k.onrender.com/webhook/keepalive || true
